kind: Service
name: 
metadata:
  labels:
    expose: "false"
    discovery.3scale.net/discoverable: "true"
  annotations:
    discovery.3scale.net/scheme: "http"
    discovery.3scale.net/description-path: "openapi.json"
spec:
  type: LoadBalancer